version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # Container base images in Containerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
